### ISSUE TITLE
Suggestion: Define a code style

### ISSUE THREAD

**Issue by andrzejp** [TomSpencerLondon/Quiz#5]
It would be good to define a code style to keep things consisten in PRs, etc. Perhaps it would be enough to commit some of the IntelliJ project settings or set up Google Java Format or Spotless, etc.

**Comment by TomSpencerLondon** [comment]
Added google-java-format here:
https://github.com/TomSpencerLondon/Quiz/commit/7ee16298cc68a7defb0e433be716cad6af5a76f6

https://google.github.io/styleguide/javaguide.html
